#!/bin/bash
#
# pqtc	This shell script takes care of starting and stopping pqtc.
#
# chkconfig: - 80 30
# description:	high performance traffic collector
#
# processname:	/usr/bin/pqtc
# pidfile:	/var/run/pqtc.pid

### BEGIN INIT INFO
# Provides: pqtc
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $network $syslog
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: start|stop|status|restart pqtc server
# Description: control pqtc server
### END INIT INFO

. /etc/sysconfig/perl-iptdaemon

#Servicename
SERVICE=pqtc
BINARY=/usr/bin/pqtc
#PIDFILE=/var/run/pqtc.pid
DAEMONARGS="-t1 -q1 -i$IPTDAEMON_INTERFACE -d/var/db/pqtc/"

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

if [ ${NETWORKING} = "no" ]
then
	exit 0
fi

[ -x $BINARY ] || exit 0

RETVAL=0

start() {
	echo -n "Starting $SERVICE: "
	daemon $BINARY $DAEMONARGS >/var/log/pqtc.log
	RETVAL=$?
	#PID=$!

	echo 
	if [ $RETVAL -eq 0 ];then
	   touch /var/lock/subsys/$SERVICE
	   #echo $PID > $PIDFILE
	else
	   exit 7;
	fi
  return 0;
}

stop() {
	echo -n "Stopping $SERVICE: "
	killproc $SERVICE
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
	   #rm -f $PIDFILE
	   rm -f /var/lock/subsys/$SERVICE
	fi
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $SERVICE
	RETVAL=$?
	;;
  restart|reload)
	restart
	;;
  condrestart)
	[ -f /var/lock/subsys/$SERVICE ] && restart || :
	;;
  *)
	echo "Usage: $SERVICE {start|stop|status|restart|reload|condrestart}"
	exit 1
esac
